CREATE TABLE IF NOT EXISTS payments (
	id VARCHAR(20) PRIMARY KEY,
	order_id VARCHAR(20) NOT NULL,
	amount NUMERIC(12,2) NOT NULL,
	status VARCHAR(20) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE IF NOT EXISTS payments_id_seq;